### PR TITLE
Added single navigation bar functionality.

### PR DESCRIPTION
**Pull request by satyamraghuwanshi136**
This PR solves issue #13 

### Things that I have done to achieve this:-

- Created custom element **"navbar.js"** file in the **"script"** directory. 
- Including this **"navbar.js"** file in all **.html** files using the **script tag**. 
- Adding the **`"<my-navbar></my-navbar>"`**  tag in the place of previous navbar code to include navbar.

@ggiande Thank you very much for letting me work on this issue.

**_let me know if I can help solve another issue. I will be happy to work._**

### CODE REVIEW

**Review by ggiande — CHANGES_REQUESTED** [review]
- [ ] Change PR to merge to development instead of main.
Undo deletions of:
- [ ] [...cfb60248508b292252e19ccd4d/Finding a gitignore file 9df54b71a63b45668dbde7c43debd544.html](https://github.com/CSClubOfStanState/csclub-website/pull/18/files#diff-e224142de4c805c437669bb623827e6893d0524aefceaffdca60569a36b0bd4c)
- [ ] [...Refactoring Fabric Clone db5528b0b1f14d80a7d162976ef2bb77/one_rename_remove.gif](https://github.com/CSClubOfStanState/csclub-website/pull/18/files#diff-dd406c4ae2b1a8bcff3ac68c34455b2eb2ed5fee215acb06bae42a435b0e3fa5)
- [ ] [...362/Refactoring Fabric Clone db5528b0b1f14d80a7d162976ef2bb77/renamed_modid.gif](https://github.com/CSClubOfStanState/csclub-website/pull/18/files#diff-ab43a612a1eaf9f654b3e80d9431f79b347f04796a6968035c31f1b18a3e6135)
- [ ] Navbar at index.html does not appear to work...

**Comment by satyamraghuwanshi136** [comment]
I have not changed the navbar of `archive.html` because We have `archive.html` in **archives** directory. we must have `archive.html` in the root directory to work.

I have solved the navbar issue but I have not updated the PR because  I am getting error while restoring the deleted file

@ggiande I am getting **_`Filename too long error`_** while restoring the files that are deleted.


filename too long

**Comment by ggiande** [comment]
I'll revise archive.html later. Long file names are blocked by default by git. I used _git config core.longpaths true_ to bypass this issue.

**Comment by satyamraghuwanshi136** [comment]
okay. should I open another PR.

**Comment by ggiande** [comment]
It doesn't look like it was merged. I believed it closed on its own. I suggest reopening the PR and referencing the following [docs on changing PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request).

**Comment by satyamraghuwanshi136** [comment]
I have opened a new PR.

**Pull request closed without merging**
